apiVersion: v1
kind: Service
metadata:
  name: customer-info
  labels:
    name: customer-info
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30005
  selector:
    name: customer-info
