apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-info
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-info
    spec:
      containers:
      - name: customer-info
        image: reactivesw/customer-info:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
        env:
        - name: spring_datasource_url
          value: jdbc:postgresql://104.155.176.8:5432/customer_info