apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-info
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-info
    spec:
      containers:
      - name: customer-info
        image: reactivesw/customer-info:0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: server_port
          value: "80"
        - name: spring_datasource_url
          value: jdbc:postgresql://pg-data/customer_info
        - name: spring_cloud_config_uri
          value: http://reactivesw-config