kind: List
apiVersion: v1
items:
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: dev
    name: customer-info
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: customer-info
      spec:
        containers:
        - name: customer-info
          image: reactivesw/customer-info:0.0.1
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: server_port
            value: "80"
          - name: spring_datasource_url
            value: jdbc:postgresql://reactivesw-data/customer_info
          - name: spring_cloud_config_uri
            value: http://reactivesw-config
          - name: jwt_secret
            value: test
- kind: Service
  apiVersion: v1
  metadata:
    name: customer-info
    namespace: dev
    labels:
      name: customer-info
  spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30105
    selector:
      name: customer-info

